// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: peer.proto

package peer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerRequest) Reset() {
	*x = GetPeerRequest{}
	mi := &file_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerRequest) ProtoMessage() {}

func (x *GetPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerRequest.ProtoReflect.Descriptor instead.
func (*GetPeerRequest) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{0}
}

func (x *GetPeerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProfilePhoto  string                 `protobuf:"bytes,2,opt,name=profile_photo,json=profilePhoto,proto3" json:"profile_photo,omitempty"`
	OnlineStatus  bool                   `protobuf:"varint,3,opt,name=online_status,json=onlineStatus,proto3" json:"online_status,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	OverallScore  uint32                 `protobuf:"varint,5,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	Interests     []string               `protobuf:"bytes,6,rep,name=interests,proto3" json:"interests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerResponse) Reset() {
	*x = GetPeerResponse{}
	mi := &file_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerResponse) ProtoMessage() {}

func (x *GetPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerResponse.ProtoReflect.Descriptor instead.
func (*GetPeerResponse) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{1}
}

func (x *GetPeerResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPeerResponse) GetProfilePhoto() string {
	if x != nil {
		return x.ProfilePhoto
	}
	return ""
}

func (x *GetPeerResponse) GetOnlineStatus() bool {
	if x != nil {
		return x.OnlineStatus
	}
	return false
}

func (x *GetPeerResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *GetPeerResponse) GetOverallScore() uint32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *GetPeerResponse) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

var File_peer_proto protoreflect.FileDescriptor

const file_peer_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"peer.proto\")\n" +
	"\x0eGetPeerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xc9\x01\n" +
	"\x0fGetPeerResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rprofile_photo\x18\x02 \x01(\tR\fprofilePhoto\x12#\n" +
	"\ronline_status\x18\x03 \x01(\bR\fonlineStatus\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12#\n" +
	"\roverall_score\x18\x05 \x01(\rR\foverallScore\x12\x1c\n" +
	"\tinterests\x18\x06 \x03(\tR\tinterests2=\n" +
	"\vPeerService\x12.\n" +
	"\aGetPeer\x12\x0f.GetPeerRequest\x1a\x10.GetPeerResponse\"\x00B*Z(ep-bridge-service/internal/genproto/peerb\x06proto3"

var (
	file_peer_proto_rawDescOnce sync.Once
	file_peer_proto_rawDescData []byte
)

func file_peer_proto_rawDescGZIP() []byte {
	file_peer_proto_rawDescOnce.Do(func() {
		file_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_proto_rawDesc), len(file_peer_proto_rawDesc)))
	})
	return file_peer_proto_rawDescData
}

var file_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_peer_proto_goTypes = []any{
	(*GetPeerRequest)(nil),  // 0: GetPeerRequest
	(*GetPeerResponse)(nil), // 1: GetPeerResponse
}
var file_peer_proto_depIdxs = []int32{
	0, // 0: PeerService.GetPeer:input_type -> GetPeerRequest
	1, // 1: PeerService.GetPeer:output_type -> GetPeerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_peer_proto_init() }
func file_peer_proto_init() {
	if File_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_proto_rawDesc), len(file_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peer_proto_goTypes,
		DependencyIndexes: file_peer_proto_depIdxs,
		MessageInfos:      file_peer_proto_msgTypes,
	}.Build()
	File_peer_proto = out.File
	file_peer_proto_goTypes = nil
	file_peer_proto_depIdxs = nil
}
