FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o streaming_service ./cmd/api

FROM alpine:latest
WORKDIR /root/

COPY --from=builder /app/streaming_service .

CMD ["./streaming_service"]
